---
- hosts: rpi
  tasks:
  - name: Copying Multiple Files
    template:
        src: "{{ item }}"
        dest: ~/
    with_fileglob:
        - templates/*
  -  name: Shell os release
     shell: ls ~/
